env:
  node: true
  es2021: true
  jest/globals: true
extends: 
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-await-in-loop: 0
plugins:
  - jest