name: tests and linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm 
      - run: make install
      - name: Run linter
        run: make lint
      - name: Unit tests
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.TEST_COVERAGE}}
        with:
          coverageCommand: make test-coverage
          debug: true
